### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by raufis27** [forty2/hap-client-tool#4]
Ubuntu 16.04

Any ideas how to solve sodium install ? 

Makefile:80: recipe for target 'nodesodium' failed
make: *** [nodesodium] Error 1
/usr/local/lib/node_modules/hap-client-tool/node_modules/sodium/install.js:287
            throw new Error(cmdLine + ' exited with code ' + code);
            ^
Error: make nodesodium exited with code 2
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/hap-client-tool/node_modules/sodium/install.js:287:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
/usr/local/lib
└── (empty)

npm ERR! Linux 4.4.0-87-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "hap-client-tool"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

**Comment by raufis27** [comment]
I was able to install it using yarn
